[tool.poetry]
name = "rns-fastapi-starter"
version = "0.1.0"
description = ""
authors = ["Ivan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
rns = "^0.8.8"
lxmf = "^0.5.8"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
fastapi = {extras = ["standard"], version = "^0.115.6"}
pydantic = "^2.10.4"
msgpack = "^1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
